In [1]:
import torch
x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

In [2]:
print(x * y)


tensor([10.,  3.])


In [3]:
zeros = torch.zeros([2,5])
print(zeros)
print(zeros.shape)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])


In [4]:
random_matrix = torch.rand([2,5])
print(random_matrix)

tensor([[0.2816, 0.2420, 0.7364, 0.9227, 0.0217],
        [0.4829, 0.7420, 0.0277, 0.0385, 0.8345]])


In [5]:
reshaped = zeros.view([1,10])
print(reshaped)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
